### ISSUE TITLE
Respawn with ak/m4

### ISSUE THREAD

**Issue by decard1337** [rogeraabbccdd/CSGO-Super-Smash-Bros#3]
When you throw the SSG at a certain time at the end of the round you will respawn with AK or M4

**Comment by rogeraabbccdd** [comment]
Hello, can you describe what is **a certain time at the end of the round**?
Or can you upload a video?

**Comment by decard1337** [comment]
So, before a new round starts, you have to spam the drop button till it drops a random weapon at the freeze time.

**Comment by rogeraabbccdd** [comment]
You should also post your settings cfg, and any error logs if you have.

**Comment by kingofings** [comment]
> 
> 
> Hello, can you describe what is **a certain time at the end of the round**?
> Or can you upload a video?

Can confirm, the issue is when the surviving players respawn in the next round there are some ticks where they still got the weapon and are able to drop it to not loose it.

This seems to work with any weapon, Primary Secondary etc.

No errors are caused during this exploit

Video demonstration. To make the replication easier host_timescale has been set to 0.5

https://youtu.be/LtmTL5_Ze4g

Ubuntu 20.04.1 LTS
Sourcemod 1.10.0.6501
Metamod 1.11.0-dev+1143

**Comment by rogeraabbccdd** [comment]
Maybe it's because the 0.1s delay timer when player spawn.
https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros/blob/e5b26a753203abe6add411103f8bfbd43e7b7d2c/scripting/kento_smashbros/events.sp#L9

**Comment by kingofings** [comment]
That's probably it imo. Maybe strip all primary weapons on round_end? Tho the weapons on the ground would need to be wiped as well so players don't pick up new ones.

**Comment by kingofings** [comment]
Nevermind the idea above. I think i have a better way of doing this. Simply change the cvar mp_death_drop_gun to 0 on round_end This causes the effect that players cannot drop their guns. After the 0.1s timer ends and gave all the weapons, change cvars value back to it's original state. there can be 1 and 2 you probably have to make the plugin remember it.
